spring:
  application:
    name: "Investment-tracker-api"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/investment-app"
          jwk-set-uri: "http://localhost:8080/realms/investment-app/protocol/openid-connect/certs"

server:
  port: 8081